#!/bin/bash
# Author
# Date
# Description: This script will check for disk space
# tail -n+2 means get rid of the first line
# cut -d% means cut out the % sign and give me the first field -f1
 
a=`df -h | egrep -v "tmpfs|devtmpfs" | tail -n+2 | awk '{print $5}' | cut -d'%' -f1`

for i in $a
do
 	if [ $i -ge 90 ]
	then
	echo check disk space | `df -h | grep $i`
	fi
done
