#!/bin/bash
# Date
# Description: This script will create a user account and check


echo "Please provise a username"
read u
echo

grep -q $u /etc/passwd	
	if [ $? -eq 0 ]
	then
	echo ERROR -- User already exist
	sleep 1
	echo please choose another username
	echo
	exit 0
	fi

useradd $u
echo $u account has been created
echo

