#!/bin/bash
# Date
# Description: This script will create a user account with description and check and specified uid

echo "Please provise a username"
read u
echo

grep -q $u /etc/passwd	
	if [ $? -eq 0 ]
	then
	echo ERROR -- User already exist
	sleep 1
	echo please choose another username
	echo
	exit 0
	fi
echo "please provide user description"
read d
echo

echo " Do you want to specified a user ID (y/n)"
read ynu
	if [ $ynu == y ]
	then
	echo " Please enter your user id "
	read uid
	useradd $u -c "$d" -u $uid
	echo
	echo $u account has beeb created
	
	elif [ $ynu == n ]
	then
	echo No worries, we will assign a UID
	useradd $u -c "$d"
	fi

