#!/bin/bash
# Date
# Description: This script will create a user account with description and check
# useradd -c will add the description to your username

echo "Please provise a username"
read u
echo

grep -q $u /etc/passwd	
	if [ $? -eq 0 ]
	then
	echo ERROR -- User already exist
	sleep 1
	echo please choose another username
	echo
	exit 0
	fi
echo "please provide user description"
read d
echo

useradd $u -c "$d"
echo $u account has been created
echo

