#!/bin/bash
# Date
# Description: This script will find dead or zombie processes and kill it.

ps -ef | grep sleep | grep -v grep | awk '{print $2}' | xargs -I{} kill {}

echo All sleeping processes are killed.
