#!/bin/bash
#
# Description: This script will logged only defined keywords
# tail -f will taill the live incomming traffic
# tail -n will look for the lastest new incomming messages
# line is our variable

tail -fn0 /var/log/messages | while read line
do
echo $line | egrep -i "refused|invalid|error|fail|shut|down|offline"
	if [ $? = 0 ]
	then
	echo $line >> /tmp/filtered-messages
	fi
done

