#!/bin/bash
# Date
# Description: this script will ping multiple remote hosts and notify


hosts="/root/udemyscript/professional-scripts/myhosts"

for ip in $(cat $hosts)

do 
	ping -c1 $ip > /dev/null
	if [ $? -eq 0 ]
	then
	echo $ip is OK
	else
	echo $ip is NOT OK
	fi
done
