#!/bin/bash
# Author: Vanessa fozin
# Date 09/24/2020
# Description: this script will pull only error messages from /var/log/messages


grep -i error /root/udemyscript/professional-scripts/messages > /root/udemyscript/professional-scripts/output-errors
