#!/bin/bash
# Author: Vanessa fozin
# Date 09/24/2020
# Description: this script will pull only error messages from /var/log/messages


grep -i fail /root/udemyscript/professional-scripts/messages1 > fail | mail -s "fail" vanessatchinda@yahoo.fr
