#!/bin/bash
#Author
#Date
#Description: This script will rename files older than 90 day. files wil have the .old extension


find /root/udemyscript/professional-scripts -mtime +90 -exec mv {} {}.old \;
